import { Controller, Get, Post, Body, Param } from '@nestjs/common';
import { EvaluationsService } from './evaluations.service';
import { ApiTags, ApiOperation, ApiParam, ApiBody } from '@nestjs/swagger';

@ApiTags('evaluations')
@Controller('evaluations')
export class EvaluationsController {
  constructor(private readonly evaluationsService: EvaluationsService) {}

  @ApiOperation({ summary: 'Get evaluations for a specific site' })
  @ApiParam({ name: 'siteId', example: '1' })
  @Get('site/:siteId')
  findBySite(@Param('siteId') siteId: string) {
    return this.evaluationsService.findBySite(+siteId);
  }

  @ApiOperation({ summary: 'Generate a new evaluation for a site' })
  @ApiParam({ name: 'siteId', example: '1' })
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        evaluation_text: { type: 'string', example: 'A levegő minősége kiváló.' },
        generated_by: { type: 'number', example: 1 },
      },
    },
  })
  @Post('generate/:siteId')
  generate(@Param('siteId') siteId: string, @Body() body: any) {
    // Evaluation may be generated by anyone, body should contain evaluation_text
    return this.evaluationsService.create(+siteId, body.evaluation_text, body.generated_by);
  }
}
